export const board=[
 {name:'Joyce Cheng',initials:'JC',role:'President',departments:['executive'],photo:'/joyce-cheng.jpeg',bio:'President',email:'chengz3594@student.laccd.edu',linkedin:'https://www.linkedin.com/in/joycecheng31'},
 {name:'Chidera Maduabuchi',initials:'CM',role:'Vice President',departments:['executive'],photo:'/chidera-maduabuchi.jpg',bio:'Vice President',email:'maduabcv5680@student.laccd.edu',linkedin:''},
 {name:'Yuna Hwang',initials:'YH',role:'Treasurer',departments:['executive'],photo:'/yuna-hwang.jpg',bio:'Treasurer',email:'hwangy8749@student.laccd.edu',linkedin:'https://www.linkedin.com/in/yunahwang721'},
 {name:'Sophia Garcia',initials:'SG',role:'Public Relations',departments:['public-relations'],photo:'/sophia-garcia.jpg',bio:'Public Relations',email:'',linkedin:''},
 {name:'Marvin Zamudio',initials:'MZ',role:'Event Coordinator',departments:['events'],photo:'/marvin-zamudio.jpg',bio:'Event Coordinator',email:'Zamudim6948@student.laccd.edu',linkedin:''},
 {name:'Emely Rosas Rugerio',initials:'ER',role:'Secretary',departments:['executive'],photo:'/emely-rosas-rugerio.jpg',bio:'Secretary',email:'rosaseg2340@student.laccd.edu',linkedin:''},
 {name:'Cindy Chen',initials:'CC',role:'Event Coordinator',departments:['events'],photo:'/cindy-chen.jpg',bio:'Event Coordinator',email:'',linkedin:''},
 {name:'Christian Arciga',initials:'CA',role:'Event Coordinator',departments:['events'],bio:'Event Coordinator',email:'',linkedin:''},
 {name:'Michael Valdez',initials:'MV',role:'ICC Delegate',departments:['icc'],photo:'/michael-valdez.jpg',bio:'ICC Delegate',email:'Valdezm4648@student.laccd.edu',linkedin:''}];
export const opportunities=[
 {type:'ELAC Resource',status:'Open',title:'Fall 2026 ELAC Student Housing at Cal State LA',organization:'East Los Angeles College',eligibility:'Furnished apartments with two students per bedroom. All-inclusive pricing starts at $1,150 per month and includes utilities, internet, and a meal plan. No transfer is required. Space is limited.',deadline:'Space limited',link:'https://bit.ly/FA26ELACStudentHousing',linkLabel:'Apply for ELAC housing',note:'Questions? Contact the ELAC Basic Needs Center.'},
 {type:'Scholarship',status:'Open',title:'Jack Kent Cooke Undergraduate Transfer Scholarship',organization:'Jack Kent Cooke Foundation',eligibility:'Up to $55,000 per year for two to three years to help community college transfer students complete a bachelor’s degree at an accredited four-year institution in the United States. Additional benefits may include transfer advising, internship and career guidance, and graduate-school planning.',deadline:'December 9, 2026',link:'https://www.commonapp.org/transfer/',linkLabel:'Apply through Common App for Transfer',note:'Essays are not required for the initial application, but advancing applicants may be asked to submit essays. Honors Societies Club is sharing this opportunity as a student resource and is not affiliated with the Jack Kent Cooke Foundation. Direct eligibility and application questions to the foundation or Common App.'}];
export const workshops=[
 {topic:'Study strategies',title:'Build a Study System That Lasts',description:'Turn a busy semester into a realistic weekly plan with active-learning techniques and peer-tested habits.',date:'September · TBD',location:'ELAC · Room TBD'},
 {topic:'Transfer preparation',title:'Your Transfer Story',description:'Map milestones, strengthen your application narrative, and prepare thoughtful questions for university representatives.',date:'October · TBD',location:'Microsoft Teams'},
 {topic:'Career development',title:'From Major to Meaningful Work',description:'Explore career paths, translate academic experience into strengths, and practice a confident introduction.',date:'November · TBD',location:'ELAC · Room TBD'}];
export const events=[
 {day:'22',month:'OCT',type:'Social Events',tags:['Social Events','General Meeting','Open to All'],confirmed:true,title:'October HSC General Meeting',description:'Meet with the board and fellow students for club updates, upcoming plans, and a chance to connect with the Honors community.',time:'12:30–1:30 PM',location:'Microsoft Teams',locationLink:'https://teams.microsoft.com/meet/242053094361812?p=DPfiRc8FW4X8wmHchU'},
 {day:'06',month:'NOV',type:'Campus Resource',tags:['Campus Resource','PIQ Workshop','Open to All'],confirmed:true,title:'UC Personal Insight Questions Workshop',description:'Build stronger UC Personal Insight Question responses through guided brainstorming, story selection, and practical peer feedback. Bring a draft for review or come ready to start from a blank page. Plan for about 90 minutes, with a two-hour maximum.',time:'3:00–4:30 PM',location:'Location TBD'},
 {day:'04',month:'DEC',type:'Social Events',tags:['Social Events','Holiday Potluck','Food & Games'],confirmed:false,title:'HSC Holiday Potluck & Game Social',description:'Celebrate the semester with food, music, team games, conversation cards, an appreciation wall, and a group photo. Bring a favorite snack or dish to share if you can—everyone is welcome, even if they cannot contribute food.',time:'12:30–2:00 PM',location:'Location TBD'},
 {day:'14–20',month:'DEC',datePrefix:'Finals Week',type:'Campus Resource',tags:['Campus Resource','Study Session','Finals Support'],confirmed:false,title:'Finals Study Jam',description:'Prepare for finals with focused study sprints, quiet work zones, collaborative problem-solving tables, study buddies, and short reset breaks. Bring your notes, assignments, and questions for a supportive study session with fellow students.',time:'Time TBD',location:'Location TBD'}];
