export const board=[
 {name:'Joyce Cheng',initials:'JC',role:'President',departments:['executive'],bio:'President',email:'chengz3594@student.laccd.edu',linkedin:'https://www.linkedin.com/in/joycecheng31'},
 {name:'Chidera Maduabuchi',initials:'CM',role:'Vice President',departments:['executive'],photo:'/chidera-maduabuchi.jpg',bio:'Vice President',email:'maduabcv5680@student.laccd.edu',linkedin:''},
 {name:'Yuna Hwang',initials:'YH',role:'Treasurer',departments:['executive'],photo:'/yuna-hwang.jpg',bio:'Treasurer',email:'hwangy8749@student.laccd.edu',linkedin:'https://www.linkedin.com/in/yunahwang721'},
 {name:'Marvin Zamudio',initials:'MZ',role:'Event Coordinator',departments:['events'],bio:'Event Coordinator',email:'Zamudim6948@student.laccd.edu',linkedin:''},
 {name:'Mersse Aguiar',initials:'MA',role:'Public Relations',departments:['public-relations'],bio:'Public Relations',email:'aguiarm6405@student.laccd.edu',linkedin:''},
 {name:'Emely Rosas Rugerio',initials:'ER',role:'Event Coordinator and Public Relations',departments:['events','public-relations'],photo:'/emely-rosas-rugerio.jpg',bio:'Event Coordinator and Public Relations',email:'rosaseg2340@student.laccd.edu',linkedin:''},
 {name:'Michael Valdez',initials:'MV',role:'ICC Delegate',departments:['icc'],bio:'ICC Delegate',email:'Valdezm4648@student.laccd.edu',linkedin:''}];
export const opportunities=[
 {type:'ELAC Resource',status:'Open',title:'Fall 2026 ELAC Student Housing at Cal State LA',organization:'East Los Angeles College',eligibility:'Furnished apartments with two students per bedroom. All-inclusive pricing starts at $1,150 per month and includes utilities, internet, and a meal plan. No transfer is required. Space is limited.',deadline:'Space limited',link:'https://bit.ly/FA26ELACStudentHousing',linkLabel:'Apply for ELAC housing',note:'Questions? Contact the ELAC Basic Needs Center.'},
 {type:'Scholarship',status:'Open',title:'Jack Kent Cooke Undergraduate Transfer Scholarship',organization:'Jack Kent Cooke Foundation',eligibility:'Up to $55,000 per year for two to three years to help community college transfer students complete a bachelor’s degree at an accredited four-year institution in the United States. Additional benefits may include transfer advising, internship and career guidance, and graduate-school planning.',deadline:'December 9, 2026',link:'https://www.commonapp.org/transfer/',linkLabel:'Apply through Common App for Transfer',note:'Essays are not required for the initial application, but advancing applicants may be asked to submit essays. Honors Societies Club is sharing this opportunity as a student resource and is not affiliated with the Jack Kent Cooke Foundation. Direct eligibility and application questions to the foundation or Common App.'}];
export const workshops=[
 {topic:'Study strategies',title:'Build a Study System That Lasts',description:'Turn a busy semester into a realistic weekly plan with active-learning techniques and peer-tested habits.',date:'September · TBD',location:'ELAC · Room TBD'},
 {topic:'Transfer preparation',title:'Your Transfer Story',description:'Map milestones, strengthen your application narrative, and prepare thoughtful questions for university representatives.',date:'October · TBD',location:'Microsoft Teams'},
 {topic:'Career development',title:'From Major to Meaningful Work',description:'Explore career paths, translate academic experience into strengths, and practice a confident introduction.',date:'November · TBD',location:'ELAC · Room TBD'}];
export const events=[
 {day:'04',month:'SEP',type:'Social Events',tags:['Social Events','Resources','Introduction to New Semester'],confirmed:true,title:'Fall Semester Kickoff!',description:'Meet the Honors Societies Club officers, discover semester resources, and start Fall 2026 with your Honors community.',time:'12:30–1:30 PM',location:'Microsoft Teams',locationLink:'https://teams.microsoft.com/meet/242053094361812?p=DPfiRc8FW4X8wmHchU'},
 {day:'22',month:'SEP',type:'Social Events',tags:['Social Events','Club Rush','⭐ STAR WARS! ⭐'],confirmed:true,title:'Club Rush',description:'Find the Honors Societies Club table, meet members, and join this semester’s Star Wars themed Club Rush.',time:'10:00 AM–2:30 PM',location:'ELAC campus · Location to be announced'}];
